In [46]:
import numpy as np

In [47]:
arr = np.array([1, 2, 3, 4, 5])

In [48]:
arr

array([1, 2, 3, 4, 5])

In [49]:
tuple1 = (1, 2, 3, 4, 5)
arr = np.array(tuple1)

In [50]:
arr

array([1, 2, 3, 4, 5])

In [51]:
#Numpy Arithmetic Operations
a = np.arange(9, dtype = np.float_).reshape(3,3)
b = np.array([11,10,10])

In [52]:
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [53]:
b

array([11, 10, 10])

In [54]:
np.add (a,b)

array([[11., 11., 12.],
       [14., 14., 15.],
       [17., 17., 18.]])

In [55]:
np.subtract (a,b)

array([[-11.,  -9.,  -8.],
       [ -8.,  -6.,  -5.],
       [ -5.,  -3.,  -2.]])

In [56]:
np.multiply (a,b)

array([[ 0., 10., 20.],
       [33., 40., 50.],
       [66., 70., 80.]])

In [57]:
np.divide(a,b)

array([[0.        , 0.1       , 0.2       ],
       [0.27272727, 0.4       , 0.5       ],
       [0.54545455, 0.7       , 0.8       ]])

In [58]:
#Numpy Arithmetic Functions
a = np.array([7,3,4,5,1])
b = np.array([3,4,5,6,7])

In [59]:
np.remainder (a,b)

array([1, 3, 4, 5, 1])

In [60]:
np.power (a,b)

array([  343,    81,  1024, 15625,     1])

In [61]:
np.mod (a,b)

array([1, 3, 4, 5, 1])

In [62]:
np.reciprocal (a)

array([0, 0, 0, 0, 1])

In [63]:
np.transpose([a,b])

array([[7, 3],
       [3, 4],
       [4, 5],
       [5, 6],
       [1, 7]])

In [64]:
a = np.array([2,5])
b = np.array([3,6])
c = np.array([4,7])
np.transpose([a,b,c])

array([[2, 3, 4],
       [5, 6, 7]])

In [68]:
import numpy as np
import numpy.matlib

In [81]:
# with the specified shape and type without initializing entries
mat_e =np.matlib.empty((3, 2), dtype = int)

In [83]:
# filled with 0
mat_zeros = np.matlib.zeros((5, 3))

In [85]:
# filled with 1
mat_ones = np.matlib.ones((4, 3))

In [86]:
# diagonal elements filled with 1, others with 0
mat_ones = np.matlib.eye(3,5)

In [87]:
# create square matrix with 0, diagonal filled with 1, others with 0
mat_zeros = np.matlib.identity(5)

In [88]:
# filled with random data
mat_e =np.matlib.empty((3, 2))

In [90]:
#The input array is stored in a disk file with the numpy.save() file and with an npy extension.
import numpy as np
a = np.array([1,2,3,4,5])
np.save('outfile',a)
# use load() function to reconstruct
import numpy as np
b = np.load('outfile.npy')
b

array([1, 2, 3, 4, 5])

In [91]:
import numpy as np
a = np.array([1,2,3,4,5])
np.savetxt('out.txt',a)
b = np.loadtxt('out.txt')
b

array([1., 2., 3., 4., 5.])