In [1]:
import numpy as np

In [2]:
a=np.array([-1,1]) 

b=np.array([1,1]) 

np.dot(a,b) 

0

In [3]:
X=np.array([[1,0],[0,1]]) 
Y=np.array([[0,1],[1,0]]) 
Z=X+Y 
Z

array([[1, 1],
       [1, 1]])

In [4]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

In [5]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]]) 
Z=np.dot(X,Y) 
Z

array([[2, 2],
       [2, 2]])

In [6]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

In [7]:
a=np.array([1,1,1,1,1]) 

a+10

array([11, 11, 11, 11, 11])